name = "Cosmologies"
uuid = "ad5277c9-dfbe-4494-be58-2d487625a7d0"
authors = ["Henry Gebhardt <hsggebhardt@fastmail.com> and contributors"]
version = "0.1.0"

[deps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
OrdinaryDiffEq = "6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
