name = "Cosmologies"
uuid = "ad5277c9-dfbe-4494-be58-2d487625a7d0"
authors = ["Henry Gebhardt <hsggebhardt@fastmail.com> and contributors"]
version = "0.1.7"

[deps]
MySplines = "b11459bf-4609-2264-00dc-5ebba822f00d"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"

[compat]
MySplines = "0.1, 0.2, 1"
OrdinaryDiffEqTsit5 = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
